### ISSUE TITLE
XUIButton的touchUpInside事件判断失败

### ISSUE THREAD

**Issue by dd2333** [HsiangHo/XUIKit#4]
另外圆角和某些属性需要每个状态如normal hover都要设置，有些麻烦，能不能没有设置就默认normal状态的呢

**Comment by HsiangHo** [comment]
@dd2333 我在Demo中测试touchUpInside事件并未发现失败的情况，我的代码如下：
[_button addActionForControlEvents:XUIControlEventTouchUpInside block:^{
        NSLog(@"TouchupInside");
    }];

**Comment by HsiangHo** [comment]
> 另外圆角和某些属性需要每个状态如normal hover都要设置，有些麻烦，能不能没有设置就默认normal状态的呢

这个是一个老问题了，我将在下次的PR，把所有没有设置的状态设置为normal状态 :)

**Comment by HsiangHo** [comment]
> 另外圆角和某些属性需要每个状态如normal hover都要设置，有些麻烦，能不能没有设置就默认normal状态的呢

@dd2333 已解决默认状态的问题，请看 #6 PR

**Comment by dd2333** [comment]
谢谢，我拉个最新代码试试，加油
